### ISSUE TITLE
Depend on ZLint master branch instead of tagged versions only

### ISSUE THREAD

**Issue by hablutzel1** [crtsh/libzlintpq#1]
I'm not really familiar with Go dependency management but it seems to me that libzlintpq is currently depending on explicitly tagged versions as you can see in:

https://github.com/crtsh/libzlintpq/blob/282fe07b6f6a15edd36ead7093d33d48311c7344/go.mod#L9

Where a dependency on an specific ZLint tagged version is observed, but, wouldn't it be possible to depend on the latest commit of the ZLint's master branch?. Maybe that is stable enough to be used directly like that.

Now, this could allow simpler review of Bugzilla bugs like https://bugzilla.mozilla.org/show_bug.cgi?id=1735247 or https://bugzilla.mozilla.org/show_bug.cgi?id=1740493, whose misissued certificates are not being caught by crt.sh right now, for example, https://crt.sh/?id=5344759725&opt=zlint now only outputs:

> NOTICE: Subscriber Certificate: commonName is deprecated. 

But doesn't include the expected:

> ERROR: FQDNs MUST consist solely of Domain Labels that are P‐Labels or Non‐Reserved LDH Labels

Finally, maybe Dependabot (https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) might help to keep the dependency on the latest ZLint (and the other linters possibly) automatically updated in this project for having crt.sh to detect issues ASAP.

**Comment by robstradling** [comment]
@hablutzel1 Automatically updating the ZLint dependency is not feasible, I'm afraid.  Each certwatch postgres instance needs to be manually stopped whilst an updated ZLint version is deployed, to ensure stability and to ensure that no postgres processes still have the old version loaded.  It takes some time to do this on all of the primary and replica systems.
Since https://github.com/zmap/zlint/issues/274 caused the primary postgres database to crash, I've been very reluctant to return to deploying the latest commit of the ZLint master branch!  It was a deliberate decision on my part to only deploy tagged ZLint versions.
